// frontend/src/components/Aside/Aside.jsx
import { NavLink, useLocation } from "react-router-dom";
import styles from "./Aside.module.css";

function Aside() {
  const urlPath = useLocation();

  return (
    <>
      <aside
        className={`${styles.aside} bg-white w-auto h-100 shadow-sm`}
      >
        <nav>
          <ul className="d-flex flex-column justify-content-between m-0 p-0 vh-100">
            <div>
              <li className="d-flex align-items-center gap-sm-3 p-2 w-100 text-decoration-none text-black border-bottom">
                <i className={`${styles.icones} bi bi-list fs-2`}></i>
                <NavLink to="/" className="text-decoration-none">
                  <h1 className={`${styles.h1} fs-4 m-0 d-none d-sm-block`}>QualiGest</h1>
                </NavLink>
              </li>
              <NavLink
                to="/projetos"
                className={`d-flex align-items-center gap-3 p-2 w-100 text-decoration-none text-black border-bottom ${urlPath.pathname == "/projetos" && styles["li-ativo"]}`}
              >
                <i className={`${styles.icones} bi bi-stack`}></i>
                <span className="d-none d-sm-block">Projetos</span>
              </NavLink>
              <NavLink
                to="/lista-tarefas"
                className={`d-flex align-items-center gap-3 p-2 w-100 text-decoration-none text-black border-bottom ${urlPath.pathname == "/lista-tarefas" && styles["li-ativo"]}`}
              >
                <i className={`${styles.icones} bi bi-check-circle-fill`}></i>
                <span className="d-none d-sm-block">Tarefas</span>
              </NavLink>
              <NavLink
                to="/detalhes-projeto"
                className={`d-flex align-items-center gap-3 p-2 w-100 text-decoration-none text-black border-bottom ${urlPath.pathname == "/detalhes-projeto" && styles["li-ativo"]}`}
              >
                <i className={`${styles.icones} bi bi-info-circle-fill`}></i>
                <span className="d-none d-sm-block">Detalhes do projeto</span>
              </NavLink>
              <NavLink
                to="/perfil"
                className={`d-flex align-items-center gap-3 p-2 w-100 text-decoration-none text-black border-bottom ${urlPath.pathname == "/perfil" && styles["li-ativo"]}`}
              >
                <i className={`${styles.icones} bi bi-person-circle`}></i>
                <span className="d-none d-sm-block">Perfil</span>
              </NavLink>
            </div>
            <NavLink to="/" className="d-flex align-items-center gap-3 p-2 w-100 text-decoration-none text-black border-top">
              <i className={`${styles.icones} bi bi-box-arrow-right`}></i>
              <span className="d-none d-sm-block">Sair</span>
            </NavLink>
          </ul>
        </nav>
      </aside>
    </>
  );
}

export default Aside;

// frontend/src/components/Aside.vue
<template>
  <aside class="bg-white w-auto d-inline-block h-100">
    <nav>
      <ul class="d-flex flex-column justify-content-between">
        <div>
          <li class="li-border">
            <i class="bi bi-list fs-2"></i>
            <router-link to="/" class="text-decoration-none">
              <h1>QualiGest</h1>
            </router-link>
          </li>
          <router-Link to="/projetos" class="li-border" :class="{ 'li-ativo': $route.path == '/projetos' }">
            <i class="bi bi-stack"></i>
            <span>Projetos</span>
          </router-Link>
          <router-Link to="/lista-tarefas" class="li-border" :class="{ 'li-ativo': $route.path == '/lista-tarefas' }">
            <i class="bi bi-check-circle-fill"></i>
            <span>Tarefas</span>
          </router-Link>
          <router-Link to="/detalhes-projeto" class="li-border" :class="{ 'li-ativo': $route.path == '/detalhes-projeto' }">
            <i class="bi bi-info-circle-fill"></i>
            <span>Detalhes do projeto</span>
          </router-Link>
          <router-Link to="/perfil" class="li-border" :class="{ 'li-ativo': $route.path == '/perfil' }">
            <i class="bi bi-person-circle"></i>
            <span>Perfil</span>
          </router-Link>
        </div>
        <router-Link to="/" class="li-border-logout">
          <i class="bi bi-box-arrow-right"></i>
          <span>Sair</span>
        </router-Link>
      </ul>
    </nav>
  </aside>
</template>

<script setup>

</script>

<style scoped>
aside {
  box-shadow: 5px 5px 5px rgba(0, 0, 0, 0.171);
  min-width: 250px;
}

ul {
  height: 100vh;
  padding: 0;
  margin: 0;
}

.li-border, .li-border-logout {
  display: flex;
  align-items: center;
  gap: 1rem;
  padding: 0.75rem 2rem;
  width: 100%;
  text-decoration: none;
  color: black;
}

.li-border{
  border-bottom: 2px solid var(--cinza-claro);  
}

.li-border-logout {
  border-top: 2px solid var(--cinza-claro);
}

h1 {
  font-size: 24px;
  color: var(--amarelo);
  margin: 0;
}

.bi {
  color: var(--amarelo);
  font-size: 20px;
}

.li-ativo {
  box-shadow: 0 -5px 5px rgba(0, 0, 0, 0.100),
              0 5px 5px rgba(0, 0, 0, 0.100);
  border-left: 5px solid var(--amarelo);
}
</style>
