// frontend/src/components/Aside.vue
<template>
  <aside class="bg-white w-auto d-inline-block h-100">
    <nav>
      <ul class="d-flex flex-column justify-content-between">
        <div>
          <li class="li-border">
            <i class="bi bi-list fs-2"></i>
            <router-link to="/" class="text-decoration-none">
              <h1>QualiGest</h1>
            </router-link>
          </li>
          <router-Link to="/projetos" class="li-border" :class="{ 'li-ativo': $route.path == '/projetos' }">
            <i class="bi bi-stack"></i>
            <span>Projetos</span>
          </router-Link>
          <router-Link to="/lista-tarefas" class="li-border" :class="{ 'li-ativo': $route.path == '/lista-tarefas' }">
            <i class="bi bi-check-circle-fill"></i>
            <span>Tarefas</span>
          </router-Link>
          <router-Link to="/detalhes-projeto" class="li-border" :class="{ 'li-ativo': $route.path == '/detalhes-projeto' }">
            <i class="bi bi-info-circle-fill"></i>
            <span>Detalhes do projeto</span>
          </router-Link>
          <router-Link to="/perfil" class="li-border" :class="{ 'li-ativo': $route.path == '/perfil' }">
            <i class="bi bi-person-circle"></i>
            <span>Perfil</span>
          </router-Link>
        </div>
        <router-Link to="/" class="li-border-logout">
          <i class="bi bi-box-arrow-right"></i>
          <span>Sair</span>
        </router-Link>
      </ul>
    </nav>
  </aside>
</template>

<script setup>

</script>

<style scoped>
aside {
  box-shadow: 5px 5px 5px rgba(0, 0, 0, 0.171);
  min-width: 250px;
}

ul {
  height: 100vh;
  padding: 0;
  margin: 0;
}

.li-border, .li-border-logout {
  display: flex;
  align-items: center;
  gap: 1rem;
  padding: 0.75rem 2rem;
  width: 100%;
  text-decoration: none;
  color: black;
}

.li-border{
  border-bottom: 2px solid var(--cinza-claro);  
}

.li-border-logout {
  border-top: 2px solid var(--cinza-claro);
}

h1 {
  font-size: 24px;
  color: var(--amarelo);
  margin: 0;
}

.bi {
  color: var(--amarelo);
  font-size: 20px;
}

.li-ativo {
  box-shadow: 0 -5px 5px rgba(0, 0, 0, 0.100),
              0 5px 5px rgba(0, 0, 0, 0.100);
  border-left: 5px solid var(--amarelo);
}
</style>

// frontend/src/components/Aside.jsx
import { NavLink, useLocation } from "react-router-dom";
import { MdCheckCircle, MdExitToApp, MdInfo, MdLayers, MdMenu, MdPersonPin } from "react-icons/md"

function Aside() {
  const urlPath = useLocation();

  function logout() {
    localStorage.clear();
  }

  return (
    <>
      <aside
        className="w-12 md:w-60 bg-white h-full shadow-md"
      >
        <nav>
          <ul className="flex flex-col justify-between p-0 h-screen">
            <div>
              <li className="flex items-center md:gap-3 p-4 w-full border-b-gray-200 border-b">
                <MdMenu className="text-amber-600 text-3xl" />
                <NavLink to="/">
                  <h1 className="text-amber-600 font-medium text-2xl hidden md:block">QualiGest</h1>
                </NavLink>
              </li>
              <NavLink
                to="/projetos"
                className={`flex items-center md:gap-3 p-3 w-full border-b-gray-200 border-b ${urlPath.pathname == "/projetos" && "shadow-md border-l-4 border-l-amber-600"}`}
              >
                <MdLayers className="text-amber-600 text-2xl" />
                <span className="hidden md:block">Projetos</span>
              </NavLink>
              { urlPath.pathname != "/projetos" &&
                <NavLink
                  to="/lista-tarefas"
                  className={`flex items-center md:gap-3 p-3 w-full border-b-gray-200 border-b ${urlPath.pathname == "/lista-tarefas" && "shadow-md border-l-4 border-l-amber-600"}`}
                >
                  <MdCheckCircle className="text-amber-600 text-xl" />
                  <span className="hidden md:block">Tarefas</span>
                </NavLink>
              }
              { urlPath.pathname != "/projetos" &&
                <NavLink
                  to="/detalhes-projeto"
                  className={`flex items-center md:gap-3 p-3 w-full border-b-gray-200 border-b ${urlPath.pathname == "/detalhes-projeto" && "shadow-md border-l-4 border-l-amber-600"}`}
                >
                  <MdInfo className="text-amber-600 text-xl" />
                  <span className="hidden md:block">Detalhes do projeto</span>
                </NavLink>
              }
              <NavLink
                to="/perfil"
                className={`flex items-center md:gap-3 p-3 w-full border-b-gray-200 border-b ${urlPath.pathname == "/perfil" && "shadow-md border-l-4 border-l-amber-600"}`}
              >
                <MdPersonPin className="text-amber-600 text-xl" />
                <span className="hidden md:block">Perfil</span>
              </NavLink>
            </div>
            <NavLink to="/" className="flex items-center md:gap-3 p-2 w-full border-t-gray-200 border-t" onClick={logout}>
              <MdExitToApp className="text-amber-600 text-xl" />
              <span className="hidden md:block">Sair</span>
            </NavLink>
          </ul>
        </nav>
      </aside>
    </>
  );
}

export default Aside;
