// frontend/src/views/DetalhesProjeto.vue
<template>
  <div class="d-flex gap-3" style="height: 100vh;">
    <Aside/>
    <main class="w-100">
      <section class="dados-projeto d-flex flex-column gap-3">
        <div class="p-3 bg-white detalhe-projeto">
          <h2>Nome do projeto</h2>
        </div>
        <div class="p-3 bg-white detalhe-projeto">
          <h2>Pontuação total: <span>500pts</span></h2>
        </div>
        <div class="d-flex gap-3 mb-3">
          <div class="p-3 bg-white w-100 detalhe-projeto">
            <h2>Tarefas Pendentes</h2>
            <p>Quantidade</p>
          </div>
          <div class="p-3 bg-white w-100 detalhe-projeto">
            <h2>Tarefas em Andamento</h2>
            <p>Quantidade</p>
          </div>
          <div class="p-3 bg-white w-100 detalhe-projeto">
            <h2>Tarefas Concluídas</h2>
            <p>Quantidade</p>
          </div>
        </div>
      </section>
      <section class="d-flex gap-3">
        <div class="ranking w-50">
          <h2>Ranking do Grupo</h2>
          <div class="d-flex justify-content-between text-center">
            <div class="flex-column ">
              <img src="../assets/images/pessoa1.jpg" alt="">
              <p class="podio">Roberto</p>
              <div class="podio">
                <i></i>
                <p>110 Pontos</p>
              </div>
            </div>
            <div>
              <img src="../assets/images/pessoa6.jpg" alt="">
              <p class="podio">Carla</p>
              <div class="podio">
                <i></i>
                <p>110 Pontos</p>
              </div>
            </div>
            <div>
              <img src="../assets/images/pessoa3.jpg" alt="">
              <p class="podio">Nicolas</p>
              <div class="podio">
                <i></i>
                <p>110 Pontos</p>
              </div>
            </div>
          </div>
        </div>       
        <table class="table w-50 text-center rounded-4">
          <thead>
            <tr>
              <th scope="col">Rank</th>
              <th scope="col"></th>
              <th scope="col">Participante</th>
              <th scope="col">Pontos</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row">4</th>
              <td>
                <img src="../assets/images/pessoa1.jpg" alt="">
              </td>
              <td>Jessica Felicio</td>
              <td>79</td>
            </tr>
            <tr>
              <th scope="row">5</th>
              <td>
                <img src="../assets/images/pessoa2.jpg" alt="">
              </td>
              <td>Charles Etorome</td>
              <td>67</td>
            </tr>
            <tr>
              <th scope="row">6</th>
              <td>
                <img src="../assets/images/pessoa3.jpg" alt="">
              </td>
              <td>Nathan Anderson</td>
              <td>54</td>
            </tr>
            <tr>
              <th scope="row">7</th>
              <td>
                <img src="../assets/images/pessoa4.jpg" alt="">
              </td>
              <td>Matthew Hamilton</td>
              <td>52</td>
            </tr>
            <tr>
              <th scope="row">8</th>
              <td>
                <img src="../assets/images/pessoa5.jpg" alt="">
              </td>
              <td>Brooke Cagle</td>
              <td>49</td>
            </tr>
            <tr>
              <th scope="row">9</th>
              <td>
                <img src="../assets/images/pessoa6.jpg" alt="">
              </td>
              <td>Ivana Cajina</td>
              <td>47</td>
            </tr>
          </tbody>
        </table>
      </section>
    </main>
  </div>
</template>
  
<script setup>
import Aside from '@/components/Aside.vue';
</script>
  
<style scoped>
.detalhe-projeto, table {
  box-shadow: 5px 5px 5px rgba(0, 0, 0, 0.171);
}

.dados-projeto h2 {
  font-size: 20px;
}

.ranking img {
  width: 150px;
  height: 150px;
  object-fit: cover;
  border-radius: 50%;
  border: 2px solid black;
}

table img {
  width: 50px;
  height: 50px;
  object-fit: cover;
  border-radius: 50%;
}

.podio {
  background-color: var(--azul);
  margin-top: 1rem;
  border-radius: .25rem;
} 
</style>

// frontend/src/pages/DetalhesProjeto.jsx
import Aside from "../components/Aside";

function DetalhesProjeto() {
  return (
    <div className="flex gap-1 sm:gap-3 h-screen">
      <Aside />
      <main className="w-full">
        <section className="flex flex-col gap-1 sm:gap-3">
          <div className="p-3 bg-white shadow-sm">
            <h2 className="text-xl">Nome do projeto</h2>
          </div>
          <div className="p-3 bg-white shadow-sm">
            <h2 className="text-lg">
              Pontuação total: <span>500pts</span>
            </h2>
          </div>
          <div className="flex flex-col lg:flex-row gap-1 sm:gap-3 mb-3">
            <div className="p-3 bg-white w-full shadow-sm">
              <h2 className="text-lg">Tarefas Pendentes</h2>
              <p>Quantidade</p>
            </div>
            <div className="p-3 bg-white w-full shadow-sm">
              <h2 className="text-lg">Tarefas em Andamento</h2>
              <p>Quantidade</p>
            </div>
            <div className="p-3 bg-white w-full shadow-sm">
              <h2 className="text-lg">Tarefas Concluídas</h2>
              <p>Quantidade</p>
            </div>
          </div>
        </section>
        <section>
          <h2 className="text-2xl font-semibold">Ranking do Grupo</h2>
          <div className="relative overflow-x-auto">
            <table className="w-full text-sm text-center rounded-2xl shadow-sm mt-2 text-gray-500">
              <thead className="text-xs text-gray-700 uppercase bg-gray-50">
                <tr>
                  <th scope="col" className="px-6 py-3">
                    Rank
                  </th>
                  <th scope="col" className="px-6 py-3 hidden sm:block"></th>
                  <th scope="col" className="px-6 py-3">
                    Participante
                  </th>
                  <th scope="col" className="px-6 py-3">
                    Pontos
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr className="bg-white border-b border-gray-200">
                  <th
                    scope="row"
                    className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap"
                  >
                    4
                  </th>
                  <td className="px-3 py-2 hidden sm:block">
                    <img
                      className="w-12 h-12 object-cover rounded-full"
                      src="/images/pessoa1.jpg"
                      alt=""
                    />
                  </td>
                  <td className="px-3 py-2">Jessica Felicio</td>
                  <td className="px-3 py-2">79</td>
                </tr>
                <tr className="bg-white border-b border-gray-200">
                  <th
                    scope="row"
                    className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap"
                  >
                    5
                  </th>
                  <td className="px-3 py-2 hidden sm:block">
                    <img
                      className="w-12 h-12 object-cover rounded-full"
                      src="/images/pessoa2.jpg"
                      alt=""
                    />
                  </td>
                  <td className="px-3 py-2">Charles Etorome</td>
                  <td className="px-3 py-2">67</td>
                </tr>
                <tr className="bg-white border-b border-gray-200">
                  <th
                    scope="row"
                    className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap"
                  >
                    6
                  </th>
                  <td className="px-3 py-2 hidden sm:block">
                    <img
                      className="w-12 h-12 object-cover rounded-full"
                      src="/images/pessoa3.jpg"
                      alt=""
                    />
                  </td>
                  <td className="px-3 py-2">Nathan Anderson</td>
                  <td className="px-3 py-2">54</td>
                </tr>
                <tr className="bg-white border-b border-gray-200">
                  <th
                    scope="row"
                    className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap"
                  >
                    7
                  </th>
                  <td className="px-3 py-2 hidden sm:block">
                    <img
                      className="w-12 h-12 object-cover rounded-full"
                      src="/images/pessoa4.jpg"
                      alt=""
                    />
                  </td>
                  <td className="px-3 py-2">Matthew Hamilton</td>
                  <td className="px-3 py-2">52</td>
                </tr>
                <tr className="bg-white border-b border-gray-200">
                  <th
                    scope="row"
                    className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap"
                  >
                    8
                  </th>
                  <td className="px-3 py-2 hidden sm:block">
                    <img
                      className="w-12 h-12 object-cover rounded-full"
                      src="/images/pessoa5.jpg"
                      alt=""
                    />
                  </td>
                  <td className="px-3 py-2">Brooke Cagle</td>
                  <td className="px-3 py-2">49</td>
                </tr>
                <tr className="bg-white border-b border-gray-200">
                  <th
                    scope="row"
                    className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap"
                  >
                    9
                  </th>
                  <td className="px-3 py-2 hidden sm:block">
                    <img
                      className="w-12 h-12 object-cover rounded-full"
                      src="/images/pessoa6.jpg"
                      alt=""
                    />
                  </td>
                  <td className="px-3 py-2">Ivana Cajina</td>
                  <td className="px-3 py-2">7</td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>
      </main>
    </div>
  );
}

export default DetalhesProjeto;
