// frontend/src/pages/Perfil.jsx
import Aside from "../components/Aside";

function Perfil() {
  return (
    <div className="flex gap-1 lg:gap-3">
      <Aside />
      <main className="h-screen w-full">
        <div className="p-3 bg-white shadow-sm mb-1 lg:mb-3">
          <h2 className="text-2xl">Perfil</h2>
        </div>
        <section className="bg-white flex justify-center items-center shadow-sm">
          <div className="max-w-5xl w-full p-3 flex flex-col gap-4">
            <div className="flex flex-col lg:flex-row gap-5">
              <img
                className="w-52 h-52 object-cover rounded-full m-auto border border-gray-500"
                src="/images/pessoa1.jpg"
                alt=""
              />
              <form className="w-full">
                <div className="mt-2">
                  <label
                    htmlFor="inputNomeCompleto"
                    className="mb-2 text-sm font-medium"
                  >
                    Nome completo
                  </label>
                  <input
                    type="text"
                    id="inputNomeCompleto"
                    className="rounded-lg bg-gray-50 border text-gray-900 w-full text-sm border-gray-300 p-2.5"
                    placeholder="Informe seu nome completo"
                    name="nome_completo"
                  />
                </div>
                <div className="mt-2">
                  <label
                    htmlFor="inputNomeUsuario"
                    className="mb-2 text-sm font-medium"
                  >
                    Usuário
                  </label>
                  <input
                    type="text"
                    id="inputNomeUsuario"
                    className="rounded-lg bg-gray-50 border text-gray-900 w-full text-sm border-gray-300 p-2.5"
                    placeholder="Informe seu nome de usuário"
                    name="nome_usuario"
                  />
                </div>
                <div className="mt-2">
                  <label
                    htmlFor="inputEmailLogin"
                    className="mb-2 text-sm font-medium"
                  >
                    E-mail
                  </label>
                  <input
                    type="text"
                    id="inputEmailLogin"
                    className="rounded-lg bg-gray-50 border text-gray-900 w-full text-sm border-gray-300 p-2.5"
                    placeholder="email@exemplo.com"
                    name="email"
                  />
                </div>
              </form>
            </div>
            <div className="flex flex-col lg:flex-row gap-4">
              <div
                className="bg-blue-200 border border-blue-300 p-4 rounded-2xl font-semibold flex items-center flex-col w-full"
              >
                <p className="text-md">Pontuação total</p>
                <span className="text-lg font-normal">0</span>
              </div>
              <div
                className="bg-blue-200 border border-blue-300 p-4 rounded-2xl font-semibold flex items-center flex-col w-full"
              >
                <p className="text-md">Tarefas concluídas</p>
                <span className="text-lg font-normal">0</span>
              </div>
              <div
                className="bg-blue-200 border border-blue-300 p-4 rounded-2xl font-semibold flex items-center flex-col w-full"
              >
                <p className="text-md">Tarefas atrasadas</p>
                <span className="text-lg font-normal">0</span>
              </div>
            </div>
            <div>
              <button type="button" className="bg-black text-white rounded-md cursor-pointer hover:bg-black/80 transition-all w-full p-2">
                Editar perfil
              </button>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}

export default Perfil;

// frontend/src/views/Perfil.vue
<template>
  <div class="d-flex gap-1 gap-lg-3">
    <Aside />
    <main class="w-100">
      <div class="p-3 bg-white header-perfil mb-1 mb-lg-3">
        <h2 class="fs-4 m-0">Perfil</h2>
      </div>
      <section class="bg-white d-flex justify-content-center align-items-center">
        <div class="div-perfil w-100 p-3 d-flex flex-column gap-4">
          <div class="d-flex flex-column flex-lg-row gap-5">
            <img class="m-auto" src="../assets/images/pessoa1.jpg" alt="">
            <form class="w-100">
              <div class="mb-3">
                <label for="emailId" class="form-label">E-mail</label>
                <input type="email" class="form-control p-2" id="emailId" placeholder="exemplo@gmail.com">
              </div>
              <div class="mb-3">
                <label for="senhaId" class="form-label">Senha</label>
                <input type="password" class="form-control p-2" id="senhaId" placeholder="*******">
              </div>
            </form>
          </div>
          <div class="d-flex flex-column flex-lg-row gap-4">
            <div class="p-4 rounded-5 fw-semibold d-flex align-items-center flex-column w-100">
              <p class="fs-6">Pontuação total</p>
              <span class="fs-3 fw-normal">0</span>
            </div>
            <div class="p-4 rounded-5 fw-semibold d-flex align-items-center flex-column w-100">
              <p class="fs-6">Tarefas concluídas</p>
              <span class="fs-3 fw-normal">0</span>
            </div>
            <div class="p-4 rounded-5 fw-semibold d-flex align-items-center flex-column w-100">
              <p class="fs-6">Tarefas atrasadas</p>
              <span class="fs-3 fw-normal">0</span>
            </div>
          </div>
          <div>
            <button type="button" class="btn btn-dark w-100 p-2">Editar perfil</button>
          </div>
        </div>
      </section>
    </main>
  </div>
</template>

<script setup>
import Aside from "@/components/Aside.vue";
</script>

<style scoped>
.header-perfil {
  box-shadow: 5px 5px 5px rgba(0, 0, 0, 0.171) !important;
}

main {
  height: 100vh;
}

.div-perfil {
  max-width: 1000px;
}

img {
  width: 200px;
  height: 200px;
  object-fit: cover;
  border-radius: 50%;
}

section {
  box-shadow: 5px 5px 5px rgba(0, 0, 0, 0.171);
}

.p-4.rounded-5 {
  background-color: var(--azul);
}

</style>
